apply plugin: 'com.android.application'

android {
    namespace 'com.aithss.installerprobe'
    compileSdk 36
    defaultConfig {
        applicationId 'com.aithss.installerprobe'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1'
    }
}
dependencies {
    implementation "androidx.core:core:$androidxCoreVersion"
}
